---
# Extends base_nodry.yaml and adds dry contact/status pins functionality
packages:
  base: !include base_nodry.yaml

switch:
  - platform: gpio
    id: "${id_prefix}_status_door"
    internal: true
    pin:
      number: ${status_door_pin} # output door status, HIGH for open, LOW for closed
      mode:
        output: true
    name: "Status door"
    entity_category: diagnostic
  - platform: gpio
    id: "${id_prefix}_status_obstruction"
    internal: true
    pin:
      number: ${status_obstruction_pin} # output for obstruction status, HIGH for obstructed, LOW for clear
      mode:
        output: true
    name: "Status obstruction"
    entity_category: diagnostic

interval:
  - interval: 100ms
    then:
      - if:
          condition:
            binary_sensor.is_on: ${id_prefix}_obstruction
          then:
            - switch.turn_on: ${id_prefix}_status_obstruction
          else:
            - switch.turn_off: ${id_prefix}_status_obstruction
      - if:
          condition:
            lambda: "return id(${id_prefix}_garage_door).position == COVER_OPEN;"
          then:
            - switch.turn_on: ${id_prefix}_status_door
          else:
            - switch.turn_off: ${id_prefix}_status_door

binary_sensor:
  - platform: gpio
    id: "${id_prefix}_dry_contact_open"
    pin:
      number: ${dry_contact_open_pin} # dry contact for opening door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact open"
    entity_category: diagnostic
    filters:
      - delayed_on_off: 500ms
    on_press:
      then:
        script.execute: "${id_prefix}_dry_contact_door_control"
  - platform: gpio
    id: "${id_prefix}_dry_contact_close"
    pin:
      number: ${dry_contact_close_pin} # dry contact for closing door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact close"
    entity_category: diagnostic
    filters:
      - delayed_on_off: 500ms
    on_press:
      then:
        script.execute: "${id_prefix}_dry_contact_door_control"
  - platform: gpio
    id: "${id_prefix}_dry_contact_light"
    pin:
      number: ${dry_contact_light_pin} # dry contact for triggering light (no discrete light commands, so toggle only)
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact light"
    entity_category: diagnostic
    filters:
      - delayed_on_off: 500ms
    on_press:
      - light.toggle: ${id_prefix}_light

script:
  - id: "${id_prefix}_dry_contact_door_control"
    then:
      - delay: 0.1s
      - if:
          condition:
            and:
              - binary_sensor.is_on: ${id_prefix}_dry_contact_close
              - binary_sensor.is_on: ${id_prefix}_dry_contact_open
          then:
            - cover.toggle: ${id_prefix}_garage_door
      - if:
          condition:
            and:
              - binary_sensor.is_off: ${id_prefix}_dry_contact_close
              - binary_sensor.is_on: ${id_prefix}_dry_contact_open
          then:
            - cover.open: ${id_prefix}_garage_door
      - if:
          condition:
            and:
              - binary_sensor.is_on: ${id_prefix}_dry_contact_close
              - binary_sensor.is_off: ${id_prefix}_dry_contact_open
          then:
            - cover.close: ${id_prefix}_garage_door
